version: "3"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: instagram
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - docker-mysql:/var/lib/mysql

volumes:
  docker-mysql: